using UnityEngine;

namespace Managers
{
    public class Services : MonoBehaviour
    {
        public static Services Instance { get; private set; }

        public SceneManager SceneManager => sceneManager;
        public BGM BGM => bgm;

        [SerializeField] private SceneManager sceneManager;
        [SerializeField] private BGM bgm;
        
        public void Awake()
        {
            if (Instance)
            {
                Destroy(gameObject);
                return;
            }
            
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
    }
}
